### PR TITLE
Add gaia passbands

### PR DESCRIPTION
**Pull request by segasai**
It addresses the #40

### CODE REVIEW

**Comment by dkirkby** [comment]
Thanks @segasai.

I checked the filter curve values and it looks like they need a bit of cleaning up:
  - Some wavelengths have transmission values of 99.99.  I suspect these lines should just be removed, unless there are special instructions about this in their documentation.
  - There are some transmission values < 0.  These should probably be dropped (in the tails) or set to zero (in case this occurs within the filter support).
  - There are some long tails with very low transmission values.  If these are consistent with zero, within the transmission measurement errors, I would drop these to avoid errors when convolving with a flux that is not specified over these long tails.  It looks like a threshold around 1e-6 would be about right.
 - Each curve should have a single zero  transmission point at each end, for a well defined linear interpolation model over the full filter support.

**Comment by segasai** [comment]
Thanks, I've fixed it. Should I put the python script that preprocess the official curves into these .ecsv somewhere in the repo ?

**Comment by dkirkby** [comment]
Thanks, this is the result of:
```
gaiadr2 = speclite.filters.load_filters('gaiadr2-*')
speclite.filters.plot_filters(gaiadr2)
```
gaiadr2

Can you confirm that the abrupt edge in G around 10500 is desired?

**Comment by dkirkby** [comment]
@segasai Can you allow me to push to your fork so I  can add this plot to the sphinx docs?

**Comment by dkirkby** [comment]
It looks like G goes smoothly to zero around 11,000A in the plot [here](https://www.cosmos.esa.int/web/gaia/iow_20180316).

**Comment by segasai** [comment]
It was a consequence of me cutting by 3sigma uncertainties. I'm updating that. I think I'll do 1 sigma

**Comment by segasai** [comment]
I've also added you @dkirkby  to my repo, so you can make commits there

**Comment by dkirkby** [comment]
Looks good now:
gaiadr2

I added this plot to the docs and I think everything is ready to merge now.

**Comment by segasai** [comment]
Thanks for merging/help!

**Comment by dkirkby** [comment]
I just tagged v0.13 and pushed the new version to [pypi](https://pypi.org/project/speclite/) so this can be easily incorporated into the next pipeline release.

**Comment by dkirkby** [comment]
Updated v0.13 docs are [here](https://speclite.readthedocs.io/en/stable/filters.html).

@sbailey Note that this release also contains updated (DR1) DECam filters.

Thanks for the contribution @segasai!

**Pull request merged**
