### PR TITLE
Migrate to Github Actions and Convert Python 2 to Python 3

### PR DESCRIPTION
**Pull request by andyyPark**
This PR moves unit tests from Travis to Github actions and converts Python 2 code to Python 3.

### CODE REVIEW

**Comment by sbailey** [comment]
Thanks.  I see the .github/workflows/python-package.yml file, but the workflow itself doesn't appear to be triggered (and the travis tests are still running).  Do we need to do something else to actually turn the GitHub Actions on?  Or is this an artifact of it being a PR from a fork instead of a branch?

**Comment by weaverba137** [comment]
Another question: how exactly does speclite deploy its documentation to ReadTheDocs?  I don't see the necessary webhook for that.

**Comment by weaverba137** [comment]
@sbailey: GitHub Actions are not being triggered because this is a PR off of a fork, not a branch.

**Comment by dkirkby** [comment]
@weaverba137 Do you have a suggestion for what we should do differently for the ReadTheDocs integration?  The docs already exist at https://speclite.readthedocs.io/en/latest/ but I have been triggering new builds manually.

**Comment by dkirkby** [comment]
@sbailey @weaverba137 Do you know if there is a way to trigger the GitHub actions on this PR, or should we just merge and see what happens?

**Comment by weaverba137** [comment]
@dkirkby, before I give a lot of advice here, let me ask: what is the long-term roadmap for this package?  Are you going to continue to support it as an Astropy-affiliated package?  Any answer I would give would depend very strongly on that.

**Comment by dkirkby** [comment]
@weaverba137 My slight preference is to abandon the astropy affiliated package ecosystem (since we are already quite out of sync) and adopt something simpler and more maintainable.  However, if you think getting back in sync with astropy is better for long-term support I am open to that also.  Whatever we decide, I would like to handle specsim the same way.

**Comment by dkirkby** [comment]
Does anyone object if I merge this now so the new GHA unit tests have a chance to run? @sbailey @weaverba137

**Comment by weaverba137** [comment]
I have no objections if you merge.  If you are abandoning astropy-affiliated status, that's fine, but then the best path forward for long-term maintainability is to adopt the DESI package layout.

As far as ReadTheDocs goes, adopting the DESI package layout will take care of a lot of that, but for the record, who is the person responsible for maintaining the RTD *account* associated with speclite.readthedocs.io?

**Comment by dkirkby** [comment]
speclite.readthedocs.io is currently under my RTD account but I am happy to transfer this or add another authorized RTD account (if that's possible).  Same for specsim.

**Comment by weaverba137** [comment]
@dkirkby as long as we know who to contact if RTD is not updating, or if some other change is required, that's all we need.

**Pull request merged**
