### PR TITLE
add 2MASS filters

### PR DESCRIPTION
**Pull request by moustakas**

### CODE REVIEW

**Comment by weaverba137** [comment]
The test is failing because it is not testing against the version of `numpy` that is specified.

Specifically, `matplotlib` is installed after `numpy`, but since no version is specified on `matplotlib`, it installs the latest version.  Then that version of `matplotlib` demands a more recent version of `numpy`, so `numpy==1.24.4` is installed over `numpy==1.19.5`.

This could be tricky to resolve, since it's not just `numpy` plus `astropy`, but `matplotlib` and `scipy` as well.  They are all inter-related.

Overall, note that the test suite is very out of date, but that's a separate issue.

**Comment by weaverba137** [comment]
I've found an install sequence that works, but now there are some numerical differences that need to be addressed, and that is something someone else will have to diagnose.

**Comment by moustakas** [comment]
It looks like the test failures have been around since https://github.com/desihub/speclite/commit/f062e39ac5d70b35f814636f91478d500b5f2ca7 in March of this year, but they ultimately appear to be associated with the update to the SDSS filters in July 2022 with (my) PR #76. 

In that PR, we renamed the default SDSS filters so they no longer had `atm` ("atmosphere") in their name and renamed the "no-atmosphere" filters, `noatm`.  Consequently, there are numerical differences between the magnitudes and colors which are synthesized with the current filters vs the numerical values hard-coded in the unit tests.

What's odd is that all the unit tests with #76 passed, but unfortunately the logs are no longer available and I'm not willing to work hard enough to set up the dependencies as they were back then.

Looking at the first numerical failure [here](https://github.com/desihub/speclite/actions/runs/5767289518/job/15636735612?pr=79):
```
061 It can be useful to work with a filter whose wavelengths have been shifted,
062 e.g. for the applications
063 in http://arxiv.org/abs/astro-ph/0205243.  This is supported with the
064 :meth:`FilterResponse.create_shifted` method, for example:
065 
066     >>> wlen = np.arange(4000, 10000) * u.Angstrom
067     >>> flux = np.ones(len(wlen)) * u.erg / (u.cm**2 * u.s * u.Angstrom)
068     >>> r0 = speclite.filters.load_filter('sdss2010-r')
069     >>> rz = r0.create_shifted(band_shift=0.2)
070     >>> print(np.round(r0.get_ab_magnitude(flux, wlen), 3))
Expected:
    -21.359
Got:
    -21.362
```

To test which number is "correct", I'm going to use the totally independent code base [sedpy](https://github.com/bd-j/sedpy). Unfortunately, it doesn't handle band-shifting, so I'll recompute at z=0:

```
import numpy as np
import astropy.units as u
import speclite.filters
from sedpy import observate

wlen = np.arange(4000, 10000) * u.Angstrom
flux = np.ones(len(wlen)) * u.erg / (u.cm**2 * u.s * u.Angstrom)

r0 = speclite.filters.load_filter('sdss2010-r')
rmag_speclite = r0.get_ab_magnitude(flux, wlen)

filt = observate.Filter('sdss_r0')
rmag_sedpy = filt.ab_mag(wlen.value, flux.value)

print(rmag_speclite, rmag_sedpy)
-21.36184538555103 -21.36103324106971
```
And as a final confirmation of my hypothesis, here's where the `-21.359` number came from:
```
rnoatm = speclite.filters.load_filter('sdss2010noatm-r')
print(rnoatm.get_ab_magnitude(flux, wlen))
-21.35892221064861
```

All the other failures appear to be directly due to the change in the SDSS filter curves, so I'm going to update the unit tests.

**Comment by moustakas** [comment]
@weaverba137, all tests now pass. 

Feel free to merge and then work on the necessary infrastructure updates. We can also close https://github.com/desihub/speclite/pull/78 but let's not delete the branch just yet, please. I will reopen a new PR with just the additional filters I need (and a few errors corrected that don't belong in the commit history).

**Comment by weaverba137** [comment]
Great detective work, thank you! I'm going to make sure the ReadTheDocs configuration is fully updated, then merge.

**Comment by weaverba137** [comment]
OK, the updated RTD configuration is passing, merging momentarily.

**Pull request merged**
