### PR TITLE
Rework transform APIs

### PR DESCRIPTION
**Pull request by dkirkby**
This PR is to review the various transform APIs and aim for more consistency and convenience.  I am starting with the redshift transform since it is the simplest.

### CODE REVIEW

**Comment by dkirkby** [comment]
The redshift API updates (#8) are now complete, although the docs still need some updates.  I am going to try using the new utility module to streamline the resampling API next.

**Comment by weaverba137** [comment]
Will this PR ever be merged? If not, can we delete the branch?

**Comment by dkirkby** [comment]
It will probably never be merged but I would like to keep this branch alive until I get a chance to see what might be worth keeping.

**Comment by weaverba137** [comment]
Thanks.  Leaving this one open.

**Comment by weaverba137** [comment]
@dkirkby have you had a chance to see what might be worth keeping on this branch?

**Comment by dkirkby** [comment]
I am fine with abandoning the code in this branch now.

**Comment by weaverba137** [comment]
OK, thank you, closing.

**Pull request closed without merging**
