### PR TITLE
Updates in preparation for next release

### LINKED ISSUE #25: pad_spectrum does not fully obey axis argument
The `FilterResponse` object's `pad_spectrum` method appears to not add elements along the correct axis. For example...

    import numpy as np, astropy.units as u, speclite.filters as filters
    # 1-dim wavelength array
    lam0 = np.arange(3800., 5500., 1.) * u.AA
    # compatible datacube shape
    flam0 = np.tile(np.ones_like(lam0.value)[..., None, None], (1, 20, 20)) * \
        u.Unit('1e-17 erg/s/cm2/AA')
    sdss = filters.load_filters('sdss2010-*')
    flam, lam = sdss.pad_spectrum(spectrum=flam0, wavelength=lam0, method='zero', axis=0)
    print(flam0.shape, lam0.shape, flam.shape, lam.shape)

which outputs `(1700, 20, 237) (1917,)` instead of `(1917, 20, 20), (1917,)`

my version is 0.5

The workaround seems to be to `np.moveaxis` from 0 ==> -1 prior to calling `pad_spectrum`, and then reversing that operation after.

### LINKED ISSUE #34: speclite.filters.get_ab_maggies alters input wavelength array?
In https://github.com/imcgreer/simqso/issues/20 @imcgreer identified an issue in which the `speclite.filters.get_ab_maggies` method appears to alter the input wavelength array.  See, specifically, [this comment](https://github.com/imcgreer/simqso/issues/20#issuecomment-350386964) and the subsequent one.  

However, I can't reproduce this with a MWE (see below).  Do you have any thoughts?

```python
import numpy as np
from speclite import filters
ff = filters.load_filters('decam2014-r')
wave = np.linspace(3000., 11000., 100)
wave2 = wave.copy()
flux = np.ones_like(wave)
_ = ff.get_ab_maggies(flux, wave)
assert(np.all(wave == wave2))
```

### LINKED ISSUE #64: Padding method not propagated for filter group
Calling `pad_spectrum`  on a `FilterSequence` does not propagate a non-default `method` arg when `pad_spectrum` is called on the individual filters.  The solution is to add `method`  below:
```
        for response in sorted_responses:
            padded_spectrum, padded_wavelength = response.pad_spectrum(
                padded_spectrum, padded_wavelength, method)
```
Thanks to Anand for reporting this.

### LINKED ISSUE #88: matplotlib deprecated `cm.get_cmap`
Hi,

It appears that matplotlib deprecated the `get_cmap` function several version back, which is breaking plotting.

https://github.com/desihub/speclite/blob/da26fc7503a0ecb1a92eb688b6bf59719303051a/speclite/filters.py#L1994

See, the following matplotlib issue:
https://github.com/matplotlib/matplotlib/issues/28349

Thanks!

### LINKED ISSUE #89: ModuleNotFoundError: No module named 'imp'
Cannot install speclite on Python 3.12, because Python 3.12 has removed the imp package.

```
Traceback (most recent call last):
        File "/home/user/desihub/speclite/astropy_helpers/setup.py", line 22, in <module>
          from astropy_helpers.version_helpers import generate_version_py  # noqa
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/desihub/speclite/astropy_helpers/astropy_helpers/version_helpers.py", line 34, in <module>
          from .distutils_helpers import is_distutils_display_option
        File "/home/user/desihub/speclite/astropy_helpers/astropy_helpers/distutils_helpers.py", line 18, in <module>
          from .utils import silence
        File "/home/user/desihub/speclite/astropy_helpers/astropy_helpers/utils.py", line 4, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
```

### PR DESCRIPTION
**Pull request by weaverba137**
This PR:

* Closes #89
* Closes #88
* Closes #64 
* Closes #34
* Closes #25
* Restores test coverage to 100%.
* Fixes the `speclite_benchmark` command.

### CODE REVIEW

**Comment by weaverba137** [comment]
Additional commentary: I tried to make as few changes as possible in this PR, and I think this is a release candidate for `v0.20`. However, I recommend that subsequent to this PR and tagging `v0.20` that a major overhaul of the package infrastructure be performed, *e.g.* removing `astropy_helpers`, minimizing the use of `setup.py`. This isn't hard, since there are plenty of examples already in the Astropy and DESI ecosystems.

**Comment by weaverba137** [comment]
Bonus: I have been able to fix #25. For both #25 and #34, the issue was that `FilterSequence.pad_spectrum` was not passing the `axis` or `method` keywords to `FilterResponse.pad_spectrum`.  *That's all!*

**Review by dkirkby — APPROVED** [review]
Looks great, thanks!

**Comment by weaverba137** [comment]
Thank you @dkirkby. I'll leave this open longer in case anyone wants to take a look: @segasai, @moustakas, @araichoor.

**Review by moustakas — APPROVED** [review]

**Review by segasai — APPROVED** [review]
I can see that you added the previously failing example to the tests, so it looks good to me in terms of fixing #34 
Thanks!

**Comment by weaverba137** [comment]
Thank you everyone, merging and tagging momentarily.

**Comment by moustakas** [comment]
Could `v0.20` be installed at NERSC, please?
```
module spider speclite

--------------------------------------------------------------------------------------------------------------------
  speclite:
--------------------------------------------------------------------------------------------------------------------
     Versions:
        speclite/main
        speclite/master
        speclite/v0.13
        speclite/v0.15
        speclite/v0.16
        speclite/v0.17
        speclite/v0.18
        speclite/v0.19
```

**Comment by weaverba137** [comment]
Done, but only for `desiconda/20240425-2.2.0`.

**Pull request merged**
