### PR TITLE
Fix install problems

### LINKED ISSUE #54: speclite v0.9 installation problems
speclite v0.9 isn't on pypi yet so I'm trying to install with pip directly from GitHub.  If I use either of these, it doesn't seem to include the filter responses:
```
pip install https://github.com/dkirkby/speclite/archive/v0.9.tar.gz
pip install git+https://github.com/dkirkby/speclite.git@v0.9#egg=speclite
```
e.g.
```
(desitest) ~ $ python -c "import speclite.filters; r = speclite.filters.load_filter('decam2014-r')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sbailey/anaconda3/envs/desitest/lib/python3.8/site-packages/speclite/filters.py", line 1918, in load_filter
    raise ValueError("No such filter '{0}' in this group.".format(name))
ValueError: No such filter 'decam2014-r' in this group.
```
However, if I clone the repo and use `python setup.py install` it seems to work fine:
```
git clone https://github.com/dkirkby/speclite
cd speclite
python setup.py install
...
python -c "import speclite.filters; r = speclite.filters.load_filter('decam2014-r')"
[no error]
```

Ideal would be to deploy to pypi so that normal `pip install speclite` works.  Otherwise it would be helpful to know a 1-liner for simple instructions about how to install speclite v0.9.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR fixes #54.

Still testing this, but preliminary indications are that correctly setting the package name in setup.cfg solves the problem.

### CODE REVIEW

**Comment by weaverba137** [comment]
These methods are now working:

* `python setup.py install` from a git clone.
* `pip install git+https://github.com/desihub/speclite.git@fix-install`

Please try your favourite method for installing.

Also trying to fix the Travis tests.

**Comment by weaverba137** [comment]
Does anyone object if we eliminate Python 2.7 tests?

**Comment by sbailey** [comment]
Installation works for me, fixing #56.  Thanks.

Yes, let's drop py 2.7 tests.  I would like to maintain support for py3.6 through 3.8, and astropy 2 through 4 for one more tag at least.

**Comment by weaverba137** [comment]
I've also eliminated the existing v0.9 tag.  I think we can re-create it when ready.

**Pull request merged**
